In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
print(arr1)

arr2 = np.array([[1,2,3],[4,5,6]],dtype = np.float32)
print(arr2)

arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]],dtype = np.float32)
print(arr3)

[1 2 3 4 5 6]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [3]:
print("Type : ",type(arr1))
print("Shape : ",arr1.shape)
print("dimension : ",arr1.ndim)
print("size : ",arr1.size)
print("data type : ",arr1.dtype)

Type :  <class 'numpy.ndarray'>
Shape :  (6,)
dimension :  1
size :  6
data type :  int64


In [4]:
print("Type : ",type(arr2))
print("Shape : ",arr2.shape)
print("dimension : ",arr2.ndim)
print("size : ",arr2.size)
print("data type : ",arr2.dtype)

Type :  <class 'numpy.ndarray'>
Shape :  (2, 3)
dimension :  2
size :  6
data type :  float32


In [5]:
print("Type : ",type(arr3))
print("Shape : ",arr3.shape)
print("dimension : ",arr3.ndim)
print("size : ",arr3.size)
print("data type : ",arr3.dtype)

Type :  <class 'numpy.ndarray'>
Shape :  (3, 3)
dimension :  2
size :  9
data type :  float32


In [6]:
arr3_int = arr3.astype(np.int32)
print(arr3_int.dtype)
print

int32


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [7]:
arr4 = np.arange(10,101)
print(arr4)
print("Shape : ",arr4.shape)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Shape :  (91,)


In [8]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((3,4),11)

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
reshaped_2D_arr2 = arr2.reshape((3,2))
print("shape into : " ,reshaped_2D_arr2.shape)
print(reshaped_2D_arr2)

shape into :  (3, 2)
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [15]:
flattened = arr3.flatten()
print(flattened)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [16]:
arr = np.array([[1,2,3],[4,5,6]])
flat1 = arr.ravel()
print(flat1)

[1 2 3 4 5 6]


In [17]:
flat2 = arr.flatten()
print(flat2)

[1 2 3 4 5 6]


In [19]:
arr = np.array([1,2,3,4])

arr2 = np.expand_dims(arr, axis=1)
print(arr2)
print(arr2.shape)


[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [16]:
import sys

list_data = list(range(100000))
numpy_data = np.array(list_data)

print("Python list size : ",sys.getsizeof(list_data) * len(list_data),"bytes")
print("Numpy array size : ",numpy_data.nbytes,"bytes")

Python list size :  80005600000 bytes
Numpy array size :  800000 bytes


In [76]:
arr = np.array([[[1,2,3]]])
print(arr.shape)

arr2 = np.squeeze(arr)
print(arr2.shape)


(1, 1, 3)
(3,)


In [27]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

c = np.concatenate((a, b), axis=0)
print(c)


[[1 2]
 [3 4]
 [5 6]]


In [86]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.stack((a, b)))


[[1 2 3]
 [4 5 6]]


In [28]:
arr = np.arange(12)
print(np.split(arr, 3))


[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [101]:
# Dataset with 5 samples and 2 features
X = np.arange(10).reshape(5, 2)
print(X)

# Add bias column (ones)
bias = np.ones((5, 1))
print(bias)
X_new = np.concatenate((bias,X), axis=1)

print(X_new)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 0. 1.]
 [1. 2. 3.]
 [1. 4. 5.]
 [1. 6. 7.]
 [1. 8. 9.]]
